include:
  - board: rtl8762gtu_kb
    shield: keychron_k1_ultra_ansi
    artifact-name: K1-Ultra-8K
    cmake-args: >-
      -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/K1-Ultra-8K.keymap
      -DEXTRA_CONF_FILE=$GITHUB_WORKSPACE/config/K1-Ultra-8K.conf
